### PR TITLE
Feature/154 add blog on upgrading slate clusters to k8s v1243

### PR DESCRIPTION
**Pull request by adamhgriffith-uofu**
See #154 for more details.

### CODE REVIEW

**Comment by adamhgriffith-uofu** [comment]
@sthapa, fixed that formatting issue. Accidentally didn't remove a copy-paste artifact.

**Comment by adamhgriffith-uofu** [comment]
As per @jstidd and @sthapa , removed the `webrick` gem again as that is not used by GitHub and servers only as a lightweight Ruby web server for local development.

**Comment by adamhgriffith-uofu** [comment]
Added @fengpinghu's notes on the SLATE ingress controller.

**Review by jstidd — COMMENTED** [review]
Looks good

**Pull request merged**
